### ISSUE TITLE
dependencies not updated with release v0.9.2

### ISSUE THREAD

**Issue by DirkEilander** [conda-forge/hydromt-feedstock#20]
Some dependencies in the meta.yml are not up to data with the [pyproject.toml](https://github.com/Deltares/hydromt/blob/v0.9.2/pyproject.toml)
- The `entrypoints` package has been replaced by `importlib_metadata`
- `universal_pathlib<0.2` has an upper bound

Not sure what the impact is, but perhaps best to create a new release? I think it is possible to create update the recipe (meta.yml) without changing the version if we increase the build number by 1, see [docs](https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-recipes)

@savente93 what do you think?

**Comment by savente93** [comment]
Good catch, I think you're right. I'll do the new Conda release tomorrow. I did the last release yesterday evening and that's when I missed this, so let's not repeat that mistake :p
